### ISSUE TITLE
2 extra output classes in ImageNet-21K

### ISSUE THREAD

**Issue by kracwarlock** [google-research/big_transfer#18]
Why are there 21843 classes when the dataset only has 21841?

**Comment by lucasb-eyer** [comment]
You could see #7 for the WordNet IDs and check which are missing? I believe these may just be two IDs that did not have any images, but I do not remember exactly.

**Comment by weiyx16** [comment]
I think the two IDs are n03931044 & n09859684

**Comment by mosjel** [comment]
Hi everyone
Can you please put the 21841 class text file. I really searched all internet but i couldn't find it. the word net id's also are 21843 numbers. 
Thank you
