### ISSUE TITLE
Mobilenetv2 & MobilenetV3 pretrained models !

### ISSUE THREAD

**Issue by dragen1860** [google-research/big_transfer#3]
Dear authors:
    Thanks for the beneficial research work! everyone doing cv will gain a lot from your pretrained models.
    AFAK, lots of friends from industry are inteseted in these mobile-friendly models. It would be great if you could publish some edge-device pretrained models, such as mobilenetv2 and mobilenetv3, which is the son of Google! Thank you!

**Comment by lucasb-eyer** [comment]
Hi, thanks for the interest.

In the paper, we show that unfortunately small models benefit less from big pre-training. We are actively working in the direction of more edge-friendly models, but as this is research, I cannot promise anything :)

**Comment by dragen1860** [comment]
Yes, it's helpful! THank you.
