### ISSUE TITLE
Transfer Learning For Detectors

### ISSUE THREAD

**Issue by abhiagwl4262** [google-research/big_transfer#30]
Hey @kolesman I have been trying to do transfer Learning for Detection. I am trying to use Resnet50-width1 Bit pretrained model as backbone of retinanet. I am not being able to use Training configuration suggested in the paper. 
[This is retinanet repo which I am using ](https://github.com/yhenon/pytorch-retinanet)

I don't have access to TPU so not using tensorflow-tpu retinanet Repo
[retinanet repo you suggested](https://github.com/tensorflow/tpu/tree/master/models/official/retinanet)

**Comment by lucasb-eyer** [comment]
This is not a question :) We cannot help with generic "I'm trying X but it doesn't work" questions so closing this, but if you have a concrete question, feel free to reopen.

**Comment by abhiagwl4262** [comment]
@lucasb-eyer Hey man, Sorry for not being accurate and descriptive. Though, I made transfer learning with Bit models working for Detectors.

**Comment by lucasb-eyer** [comment]
Great to hear you got it working, thanks for the update!
