### ISSUE TITLE
How to download ImageNet21K dataset?

### ISSUE THREAD

**Issue by FredHuang16** [google-research/big_transfer#41]
The original download link of ImageNet21k dataset (http://image-net.org/download-imageurls)  is broken. Could you please share your downloading solution?

**Comment by ain-soph** [comment]
There are some backup torrents on the websites. [Link](https://academictorrents.com/collection/imagenet) 
But not quite sure if downloading it is legal. If it's not, notify me and I'll remove this message.

**Comment by FredHuang16** [comment]
> There are some backup torrents on the websites. [Link](https://academictorrents.com/collection/imagenet)
> But not quite sure if downloading it is legal. If it's not, notify me and I'll remove this message.

OK, thanks.
